import XCTest
@testable import MiniEngine

// ---------------------------------------------------------------------------
// OracleTests — load fixtures generated by oracle/generate.mjs and compare
// against the Swift MiniEngine.
//
// Ignored oracle fields (documented):
//   • hap.whole — we compare hap.part and hap.value; whole structure matches
//     semantically but the oracle sometimes includes the full structural span
//     while our engine clips to the queried span on part.
//   • Extra value fields that Strudel adds internally (none in our fixture set).
// ---------------------------------------------------------------------------

// MARK: - JSON models

struct FixtureSpan: Decodable {
    let begin: String
    let end: String
}

struct FixtureHap: Decodable {
    let whole: FixtureSpan?
    let part: FixtureSpan
    /// Value may be a dict (ControlPattern fixture) or a bare number (signal fixture).
    /// Signal segment fixtures have bare numeric values; they are skipped in testOracleFixtures.
    let value: [String: JSONValue]

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        whole = try container.decodeIfPresent(FixtureSpan.self, forKey: .whole)
        part  = try container.decode(FixtureSpan.self, forKey: .part)
        // Value may be a dict or a bare number (signal segment fixture).
        // For bare numbers, produce an empty dict so the fixture can be decoded
        // without crashing; signal segment fixtures are skipped in the test.
        if let dict = try? container.decode([String: JSONValue].self, forKey: .value) {
            value = dict
        } else {
            // Bare numeric value (e.g. signal segment fixture) — store as empty dict.
            // The fixture will be skipped in testOracleFixtures (skipPatterns set).
            value = [:]
        }
    }

    private enum CodingKeys: String, CodingKey {
        case whole, part, value
    }
}

struct Fixture: Decodable {
    let pattern: String
    let span: [Int]
    let haps: [FixtureHap]
}

// Flexible JSON value decoder
enum JSONValue: Decodable, Equatable {
    case string(String)
    case double(Double)
    case int(Int)

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let v = try? c.decode(String.self) { self = .string(v); return }
        if let v = try? c.decode(Int.self)    { self = .int(v);    return }
        if let v = try? c.decode(Double.self) { self = .double(v); return }
        throw DecodingError.dataCorruptedError(in: c, debugDescription: "Unexpected JSON value type")
    }

    var doubleValue: Double? {
        switch self {
        case .double(let d): return d
        case .int(let i):    return Double(i)
        case .string:        return nil
        }
    }

    var stringValue: String? {
        if case .string(let s) = self { return s }
        return nil
    }
}

// MARK: - Rational parsing helper

func parseRational(_ s: String) -> Rational? {
    let parts = s.split(separator: "/")
    guard parts.count == 2,
          let n = Int(parts[0]),
          let d = Int(parts[1]) else { return nil }
    return Rational(n, d)
}

// MARK: - Test

final class OracleTests: XCTestCase {

    var fixtures: [Fixture] = []

    override func setUpWithError() throws {
        // Load oracle_fixtures.json from the test bundle
        guard let url = Bundle.module.url(
            forResource: "oracle_fixtures",
            withExtension: "json",
            subdirectory: "Fixtures"
        ) else {
            throw XCTSkip("oracle_fixtures.json not found — run oracle/generate.mjs first")
        }
        let data = try Data(contentsOf: url)
        fixtures = try JSONDecoder().decode([Fixture].self, from: data)
    }

    func testOracleFixtures() throws {
        XCTAssertFalse(fixtures.isEmpty, "No fixtures loaded")

        let parser = CodeParser()
        var totalHaps = 0
        var mismatches: [(String, String)] = []

        // Signal-segment fixtures (sine.segment, saw.range.segment, etc.) are not
        // CodeParser code strings — they produce Pattern<Double>, not ControlPattern.
        // They are verified in SignalTests.swift (testOracleSine*, testOracleSaw*).
        let skipPatterns: Set<String> = [
            "sine.segment(8)",
            "saw.range(2,4).segment(4)",
            "sine.slow(2).segment(8)",
        ]

        for fixture in fixtures {
            // Skip signal-only (non-control) fixtures
            if skipPatterns.contains(fixture.pattern) { continue }

            let pattern: ControlPattern
            do {
                pattern = try parser.parse(fixture.pattern)
            } catch {
                XCTFail("Parse failed for: \(fixture.pattern)\n  Error: \(error)")
                continue
            }

            let spanBegin = Rational(0)
            let spanEnd   = Rational(fixture.span.last ?? 1)
            let swiftHaps = pattern.queryArc(spanBegin, spanEnd)

            // Compare count
            let expectedCount = fixture.haps.count
            let actualCount   = swiftHaps.count

            if expectedCount != actualCount {
                let msg = "[\(fixture.pattern)] hap count: expected \(expectedCount), got \(actualCount)"
                mismatches.append((fixture.pattern, msg))
                XCTFail(msg)
                continue
            }

            totalHaps += actualCount

            // Sort both by part.begin for comparison
            let oracleSorted = fixture.haps.sorted {
                (parseRational($0.part.begin) ?? .zero) < (parseRational($1.part.begin) ?? .zero)
            }
            let swiftSorted = swiftHaps.sorted { $0.part.begin < $1.part.begin }

            for (idx, (oracleHap, swiftHap)) in zip(oracleSorted, swiftSorted).enumerated() {
                // Compare part.begin
                if let expectedBegin = parseRational(oracleHap.part.begin) {
                    XCTAssertEqual(
                        swiftHap.part.begin, expectedBegin,
                        "[\(fixture.pattern)] hap[\(idx)] part.begin: expected \(expectedBegin), got \(swiftHap.part.begin)"
                    )
                }
                // Compare part.end
                if let expectedEnd = parseRational(oracleHap.part.end) {
                    XCTAssertEqual(
                        swiftHap.part.end, expectedEnd,
                        "[\(fixture.pattern)] hap[\(idx)] part.end: expected \(expectedEnd), got \(swiftHap.part.end)"
                    )
                }
                // Compare value fields
                compareValues(
                    expected: oracleHap.value,
                    actual:   swiftHap.value,
                    context:  "[\(fixture.pattern)] hap[\(idx)]"
                )
            }
        }

        print("[OracleTests] Verified \(fixtures.count) fixtures, \(totalHaps) total haps")
        if !mismatches.isEmpty {
            print("[OracleTests] Mismatches:")
            for (pat, msg) in mismatches {
                print("  \(pat): \(msg)")
            }
        }
    }

    // MARK: - Value comparison

    private func compareValues(
        expected: [String: JSONValue],
        actual:   [String: ControlValue],
        context:  String
    ) {
        for (key, expectedVal) in expected {
            guard let actualVal = actual[key] else {
                XCTFail("\(context): missing key '\(key)'")
                continue
            }
            switch expectedVal {
            case .string(let s):
                XCTAssertEqual(
                    actualVal.stringValue, s,
                    "\(context): key '\(key)' expected '\(s)', got \(actualVal)"
                )
            case .double(let d):
                if let actualD = actualVal.doubleValue {
                    XCTAssertEqual(
                        actualD, d, accuracy: 1e-9,
                        "\(context): key '\(key)' expected \(d), got \(actualD)"
                    )
                } else {
                    XCTFail("\(context): key '\(key)' expected double \(d), got \(actualVal)")
                }
            case .int(let i):
                if let actualD = actualVal.doubleValue {
                    XCTAssertEqual(
                        actualD, Double(i), accuracy: 1e-9,
                        "\(context): key '\(key)' expected \(i), got \(actualD)"
                    )
                } else {
                    XCTFail("\(context): key '\(key)' expected int \(i), got \(actualVal)")
                }
            }
        }
        // Note: we intentionally DON'T fail on extra keys in `actual` that the
        // oracle didn't include — forward-compat for extra metadata fields.
    }
}
