import Foundation

// ---------------------------------------------------------------------------
// AppBundle — robust accessor for the SPM resource bundle.
//
// SPM's autogenerated Bundle.module only searches:
//   (a) Bundle.main.bundleURL / DemoStrudel_DemoStrudelApp.bundle
//   (b) an absolute path into the developer's .build directory
// Neither exists in a distributed .app (the bundle lives in
// Contents/Resources/), so Bundle.module fatal-errors on any other Mac.
// This accessor searches the distribution path first and only falls back
// to Bundle.module for local development (swift run / .build present).
// ---------------------------------------------------------------------------

enum AppBundle {
    static let spmBundleName = "DemoStrudel_DemoStrudelApp.bundle"

    static let resources: Bundle = {
        let candidates: [URL?] = [
            Bundle.main.resourceURL?.appendingPathComponent(spmBundleName),
            Bundle.main.bundleURL.appendingPathComponent(spmBundleName),
            Bundle.main.bundleURL.appendingPathComponent("../Resources/\(spmBundleName)").standardized,
        ]
        for case let url? in candidates {
            if let bundle = Bundle(url: url) { return bundle }
        }
        return Bundle.module   // dev fallback (.build on this machine)
    }()
}
